import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import profilepic from "../../public/images/leo.jpg";

export default function Home() {
  return (
    <div className="min-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-[100vh] bg-black text-white ">
        <Navbar />
        <div className="container mx-auto px-4">
          <div className="w-full px-4 mx-auto flex items-center justify-center flex-col md:flex-row h-screen">
            <div className="w-full md:w-[50%] pt-[40px] flex flex-col items-left text-center md:text-left justify-center">
              <h1 className="md:w-[90%] text-[68px] md:text-[52px] font-bold leading-[4rem] mb-[28px] text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-pink-600">
                Frontend & No Code Developer
              </h1>
              <p className="text-[20px] md:w-[80%]">
                Hi, My name is Leo. I am a remote frontend software developer
                who loves creating beautiful user experiences.
              </p>

              <div className="w-full md:w-[60%] py-[60px]">
                <button className="text-white  bg-gradient-to-r from-purple-400 to-pink-600 py-4 px-6 rounded-lg uppercase">
                  Check out my work
                </button>
              </div>
            </div>
            <div className="hidden md:flex items-center justify-center">
              <Image
                src={profilepic}
                width={400}
                height={400}
                className="rounded-lg"
              />
            </div>
          </div>
        </div>
        <footer className="container mx-auto px-4 border-t-2 border-gray-600 opacity-25 flex items-center justify-center h-[60px] uppercase">
          © 2022 Leonard Rwai Kanyesigye
        </footer>
      </main>
    </div>
  );
}
